version: '2.1'
services:
  app:
    container_name: app
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./api:/var/www/html
#    working_dir: /var/www/html/public
    environment:
      - DB_HOST=api_db
      - MYSQL_PORT=3306
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - APP_ENV=development
      - WEB_DOCUMENT_ROOT=/var/www/html/public
  app_db:
    image: mysql:5.6
    container_name: api_db
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cidadao